#!/bin/bash
# Alert Framework - Pluggable notification system

set -euo pipefail

ALERT_LOG="/var/log/pbp/alerts.log"
POLICY_FILE="/opt/pbp/config/policy.yaml"

mkdir -p "$(dirname "$ALERT_LOG")"

# Get alert methods from policy
get_alert_methods() {
    grep -A 5 "^  methods:" "$POLICY_FILE" | grep "^    -" | sed 's/^    - //'
}

# Send alert
send_alert() {
    local severity="$1"
    local title="$2"
    local message="$3"
    local timestamp=$(date -Iseconds)
    
    # Log alert
    cat >> "$ALERT_LOG" << EOF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[PBP ALERT - $severity]
Time: $timestamp
Title: $title
Message: $message
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF

    # Send to configured methods
    for method in $(get_alert_methods); do
        case "$method" in
            terminal)
                alert_terminal "$severity" "$title" "$message"
                ;;
            log)
                # Already logged above
                ;;
            report)
                alert_report "$severity" "$title" "$message"
                ;;
            email)
                alert_email "$severity" "$title" "$message"
                ;;
            webhook)
                alert_webhook "$severity" "$title" "$message"
                ;;
        esac
    done
}

# Terminal alert
alert_terminal() {
    local severity="$1"
    local title="$2"
    local message="$3"
    
    if [[ -t 1 ]]; then
        case "$severity" in
            CRITICAL) icon="🔴" ;;
            HIGH) icon="🟠" ;;
            MEDIUM) icon="🟡" ;;
            LOW) icon="🟢" ;;
            *) icon="ℹ️" ;;
        esac
        
        echo "$icon [$severity] $title"
        echo "   $message"
    fi
}

# Report alert
alert_report() {
    local severity="$1"
    local title="$2"
    local message="$3"
    local timestamp=$(date +%Y%m%d_%H%M%S)
    local report_dir="/var/log/pbp/reports/alerts"
    
    mkdir -p "$report_dir"
    
    cat > "$report_dir/alert_${timestamp}.txt" << EOF
PBP Security Alert
==================

Severity: $severity
Time: $(date -Iseconds)
Title: $title

Details:
$message

Generated by: PBP Alert Framework
EOF
}

# Email alert (placeholder)
alert_email() {
    # Future implementation
    :
}

# Webhook alert (placeholder)
alert_webhook() {
    # Future implementation
    :
}

# Export functions
export -f send_alert alert_terminal alert_report
