#!/bin/bash

# Parrot Booty Protection - Port Hardener (The Cannon Master)
# Purpose: Man the cannons! Interactively generate a zero-trust nftables.conf file.
# Usage: sudo ./port_harden.sh

set -euo pipefail

# --- Configuration & Setup ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[0;34m'
NC='\033[0m'

NFT_CONFIG_PATH="configs/nftables.conf"

# --- Logging & UI Functions ---
log() { echo -e "${GREEN}[INFO] $1${NC}"; }
warn() { echo -e "${YELLOW}[WARN] $1${NC}"; }
step() { echo -e "\n${CYAN}--- $1 ---${NC}"; }
ask() {
    local prompt="$1"
    local default=${2:-"y"}
    local answer
    while true; do
        read -p "$(echo -e "${BLUE}$prompt [Y/n]: ${NC}")" answer
        answer=${answer:-$default}
        case $answer in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}
ask_ports() {
    local prompt="$1"
    read -p "$(echo -e "${BLUE}$prompt (e.g., 8080, 3000-3010): ${NC}")" ports
    echo "$ports"
}


# --- Helper Functions ---
require_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}This script must be run as root.${NC}"
        exit 1
    fi
}

# --- Main Logic ---
main() {
    require_root
    
    echo -e "${CYAN}🏴‍☠️ Welcome to Parrot Booty Protection: Port Hardener${NC}"
    echo "This script will help you configure a zero-trust firewall."

    # Check for existing refined configuration
    if [ -f "$NFT_CONFIG_PATH" ]; then
        step "Existing Configuration Detected"
        log "Found a refined nftables configuration at $NFT_CONFIG_PATH"
        echo "This configuration likely contains specific rules for DNS-over-TLS, NTP, and AI development tools."
        
        if ask "Do you want to apply this existing configuration (Recommended)?"; then
            log "Applying existing firewall rules from $NFT_CONFIG_PATH..."
            nft -f "$NFT_CONFIG_PATH"
            log "✅ Firewall rules applied successfully."
            
            if ask "Do you want to enable the nftables service to make these rules persistent across reboots?"; then
                systemctl enable nftables
                log "✅ nftables service enabled."
            else
                 warn "Rules are active but will be lost on reboot. Run 'sudo systemctl enable nftables' later to persist."
            fi
            
            echo -e "\n${GREEN}Port hardening complete.${NC}"
            exit 0
        fi
        log "Proceeding to generate a new generic configuration..."
    fi

    local ruleset="# Generated by Port Hardening Wizard v1.0 on $(date)\n"
    ruleset+="flush ruleset\n\n"
    ruleset+="table inet filter {\n"
    ruleset+="    # Default drop policy (Zero Trust)\n"
    ruleset+="    chain input { type filter hook input priority 0; policy drop; }\n"
    ruleset+="    chain forward { type filter hook forward priority 0; policy drop; }\n"
    ruleset+="    chain output { type filter hook output priority 0; policy drop; }\n\n"
    
    ruleset+="    # --- Essential Core Rules (Always Active) ---\n"
    ruleset+="    chain input {\n"
    ruleset+="        # Allow loopback traffic\n"
    ruleset+="        iifname \"lo\" accept\n"
    ruleset+="        # Allow established/related connections\n"
    ruleset+="        ct state established,related accept\n"
    ruleset+="    }\n"
    ruleset+="    chain output {\n"
    ruleset+="        # Allow loopback traffic\n"
    ruleset+="        oifname \"lo\" accept\n"
    ruleset+="        # Allow established/related connections\n"
    ruleset+="        ct state established,related accept\n"
    ruleset+="    }\n\n"

    local output_rules=""
    local input_rules=""

    step "1. Standard Outgoing Traffic"
    if ask "Allow outgoing web traffic (HTTP/HTTPS, port 80, 443)?"; then
        output_rules+="        # Allow web traffic\n"
        output_rules+="        tcp dport { 80, 443 } accept\n"
    fi
    if ask "Allow outgoing DNS traffic (DNS/DoT, port 53, 853)?"; then
        output_rules+="        # Allow DNS lookups\n"
        output_rules+="        udp dport 53 accept\n"
        output_rules+="        tcp dport { 53, 853 } accept\n"
    fi

    step "2. Secure Time Sync (NTP/NTS)"
    if ask "Allow outgoing secure time sync (NTP/NTS, ports 123/4460)?"; then
        output_rules+="        # Allow NTP/NTS time sync\n"
        output_rules+="        udp dport 123 accept\n"
        output_rules+="        tcp dport 4460 accept\n"
    fi

    step "3. Standard Incoming Traffic"
    if ask "Allow incoming SSH (port 22)?"; then
        input_rules+="        # Allow SSH connections\n"
        input_rules+="        tcp dport 22 accept\n"
    fi
    if ask "Allow Ping/ICMP requests?"; then
        input_rules+="        # Allow ICMP (Ping)\n"
        input_rules+="        ip protocol icmp icmp type echo-request accept\n"
    fi

    step "3. Custom Ports"
    if ask "Do you need to allow any other outgoing TCP ports?"; then
        local custom_tcp=$(ask_ports "Enter outgoing TCP ports to allow")
        if [ -n "$custom_tcp" ]; then
            output_rules+="        # Custom TCP ports\n"
            output_rules+="        tcp dport { $custom_tcp } accept\n"
        fi
    fi
    if ask "Do you need to allow any other outgoing UDP ports?"; then
        local custom_udp=$(ask_ports "Enter outgoing UDP ports to allow")
        if [ -n "$custom_udp" ]; then
            output_rules+="        # Custom UDP ports\n"
            output_rules+="        udp dport { $custom_udp } accept\n"
        fi
    fi

    # Assemble the final ruleset
    ruleset+="    # --- User-Defined Rules ---\n"
    if [ -n "$input_rules" ]; then
        ruleset+="    chain input {\n$input_rules    }\n"
    fi
    if [ -n "$output_rules" ]; then
        ruleset+="    chain output {\n$output_rules    }\n"
    fi
    ruleset+="}\n"
    
    step "4. Configuration Generation"
    log "nftables configuration generated."
    echo -e "Saving config to ${YELLOW}$NFT_CONFIG_PATH${NC}"
    echo -e "$ruleset" > "$NFT_CONFIG_PATH"
    
    echo -e "\n${BLUE}--- Generated nftables.conf ---"
    echo -e "$ruleset"
    echo -e "--- End of config ---${NC}"

    step "5. Apply Configuration"
    if ask "Do you want to apply this firewall configuration now?"; then
        log "Applying new firewall rules..."
        nft -f "$NFT_CONFIG_PATH"
        log "✅ Firewall rules applied successfully."
        warn "These rules are NOT persistent across reboots yet."
        warn "Enable the nftables service to make them persistent: sudo systemctl enable nftables"
    else
        log "Configuration saved. You can apply it later with: sudo nft -f $NFT_CONFIG_PATH"
    fi

    echo -e "\n${GREEN}Port hardening wizard finished.${NC}"
}

main "$@"
